import { PrismaClient } from '@prisma/client'
import Head from 'next/head'
import { useState } from 'react'

export const getStaticProps = async () => {
  const prisma = new PrismaClient({ log: ['query'] })
  const users = await prisma.user.findMany()

  return {
    props: { users },
  }
}

export default function Home(props) {
  const { users } = props

  const [email, setEmail] = useState('')

  return (
    <div>
      <Head>
        <title>Learn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ textAlign: 'center' }}>
        <h1>Hello Next.js</h1>
        <input
          type='text'
          value={email}
          onChange={(el) => setEmail(el.target.value)}
        />

        <div>
          {users?.map((post) => (
            <div key={post.id}>
              <h1>{post.name}</h1>
              <p>{post.email}</p>
            </div>
          ))}

          <button>create</button>
        </div>
      </div>
    </div>
  )
}
